---
- hosts: all
  become: true
  vars:
    tools:
      - jq
      - git
      - tree
      - curl
      - cowsay
      - inotify-tools
      - make
      - gcc
      - libyaml-dev
      - libssl-dev
  roles:
    - {role: tools, tag: ['dev']}
    - {role: helm, tag: ['dev']}
    - {role: yq, tag: ['dev']}
    - {role: golang, tag: ['dev']}
    - {role: erlang, tag: ['dev']}
